<?php

namespace ContainerDzARamB;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_OmhmvDService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.omhmvD_' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.omhmvD_'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'category' => ['services', 'App\\Repository\\CategoryRepository', 'getCategoryRepositoryService', true],
        ], [
            'category' => 'App\\Repository\\CategoryRepository',
        ]);
    }
}
