<?php

namespace ContainerAPFWrOF;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_WGAA0gVService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.WGAA0gV' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.WGAA0gV'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\admin\\CategoryController::index' => ['privates', '.service_locator.omhmvD_', 'get_ServiceLocator_OmhmvDService', true],
            'App\\Controller\\admin\\CategoryController::new' => ['privates', '.service_locator.Q5HBKt_', 'get_ServiceLocator_Q5HBKtService', true],
            'App\\Controller\\admin\\LoginAdminController::index' => ['privates', '.service_locator.rSTd.nA', 'get_ServiceLocator_RSTd_NAService', true],
            'App\\Controller\\admin\\ProductController::index' => ['privates', '.service_locator.E0YnTc5', 'get_ServiceLocator_E0YnTc5Service', true],
            'App\\Controller\\admin\\ProductController::new' => ['privates', '.service_locator.op4M7xK', 'get_ServiceLocator_Op4M7xKService', true],
            'App\\Controller\\user\\BuyController::index' => ['privates', '.service_locator.qcokgid', 'get_ServiceLocator_QcokgidService', true],
            'App\\Controller\\user\\BuyController::setNotificationUrl' => ['privates', '.service_locator.6awHTOw', 'get_ServiceLocator_6awHTOwService', true],
            'App\\Controller\\user\\BuyVacinController::index' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\user\\CartController::add' => ['privates', '.service_locator.CEbZ_nO', 'get_ServiceLocator_CEbZNOService', true],
            'App\\Controller\\user\\CartController::remove' => ['privates', '.service_locator.cGqsU0U', 'get_ServiceLocator_CGqsU0UService', true],
            'App\\Controller\\user\\CartController::view' => ['privates', '.service_locator.cGqsU0U', 'get_ServiceLocator_CGqsU0UService', true],
            'App\\Controller\\user\\CategoryController::index' => ['privates', '.service_locator.3opkxl5', 'get_ServiceLocator_3opkxl5Service', true],
            'App\\Controller\\user\\LoginController::index' => ['privates', '.service_locator.rSTd.nA', 'get_ServiceLocator_RSTd_NAService', true],
            'App\\Controller\\user\\PaymentController::reference' => ['privates', '.service_locator.k1cqMOm', 'get_ServiceLocator_K1cqMOmService', true],
            'App\\Controller\\user\\ProductsController::FindId' => ['privates', '.service_locator.czOFGB2', 'get_ServiceLocator_CzOFGB2Service', true],
            'App\\Controller\\user\\ProductsController::index' => ['privates', '.service_locator.czOFGB2', 'get_ServiceLocator_CzOFGB2Service', true],
            'App\\Controller\\user\\UserController::register' => ['privates', '.service_locator.e_4zbH4', 'get_ServiceLocator_E4zbH4Service', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Controller\\admin\\CategoryController:index' => ['privates', '.service_locator.omhmvD_', 'get_ServiceLocator_OmhmvDService', true],
            'App\\Controller\\admin\\CategoryController:new' => ['privates', '.service_locator.Q5HBKt_', 'get_ServiceLocator_Q5HBKtService', true],
            'App\\Controller\\admin\\LoginAdminController:index' => ['privates', '.service_locator.rSTd.nA', 'get_ServiceLocator_RSTd_NAService', true],
            'App\\Controller\\admin\\ProductController:index' => ['privates', '.service_locator.E0YnTc5', 'get_ServiceLocator_E0YnTc5Service', true],
            'App\\Controller\\admin\\ProductController:new' => ['privates', '.service_locator.op4M7xK', 'get_ServiceLocator_Op4M7xKService', true],
            'App\\Controller\\user\\BuyController:index' => ['privates', '.service_locator.qcokgid', 'get_ServiceLocator_QcokgidService', true],
            'App\\Controller\\user\\BuyController:setNotificationUrl' => ['privates', '.service_locator.6awHTOw', 'get_ServiceLocator_6awHTOwService', true],
            'App\\Controller\\user\\BuyVacinController:index' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\user\\CartController:add' => ['privates', '.service_locator.CEbZ_nO', 'get_ServiceLocator_CEbZNOService', true],
            'App\\Controller\\user\\CartController:remove' => ['privates', '.service_locator.cGqsU0U', 'get_ServiceLocator_CGqsU0UService', true],
            'App\\Controller\\user\\CartController:view' => ['privates', '.service_locator.cGqsU0U', 'get_ServiceLocator_CGqsU0UService', true],
            'App\\Controller\\user\\CategoryController:index' => ['privates', '.service_locator.3opkxl5', 'get_ServiceLocator_3opkxl5Service', true],
            'App\\Controller\\user\\LoginController:index' => ['privates', '.service_locator.rSTd.nA', 'get_ServiceLocator_RSTd_NAService', true],
            'App\\Controller\\user\\PaymentController:reference' => ['privates', '.service_locator.k1cqMOm', 'get_ServiceLocator_K1cqMOmService', true],
            'App\\Controller\\user\\ProductsController:FindId' => ['privates', '.service_locator.czOFGB2', 'get_ServiceLocator_CzOFGB2Service', true],
            'App\\Controller\\user\\ProductsController:index' => ['privates', '.service_locator.czOFGB2', 'get_ServiceLocator_CzOFGB2Service', true],
            'App\\Controller\\user\\UserController:register' => ['privates', '.service_locator.e_4zbH4', 'get_ServiceLocator_E4zbH4Service', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
        ], [
            'App\\Controller\\admin\\CategoryController::index' => '?',
            'App\\Controller\\admin\\CategoryController::new' => '?',
            'App\\Controller\\admin\\LoginAdminController::index' => '?',
            'App\\Controller\\admin\\ProductController::index' => '?',
            'App\\Controller\\admin\\ProductController::new' => '?',
            'App\\Controller\\user\\BuyController::index' => '?',
            'App\\Controller\\user\\BuyController::setNotificationUrl' => '?',
            'App\\Controller\\user\\BuyVacinController::index' => '?',
            'App\\Controller\\user\\CartController::add' => '?',
            'App\\Controller\\user\\CartController::remove' => '?',
            'App\\Controller\\user\\CartController::view' => '?',
            'App\\Controller\\user\\CategoryController::index' => '?',
            'App\\Controller\\user\\LoginController::index' => '?',
            'App\\Controller\\user\\PaymentController::reference' => '?',
            'App\\Controller\\user\\ProductsController::FindId' => '?',
            'App\\Controller\\user\\ProductsController::index' => '?',
            'App\\Controller\\user\\UserController::register' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\admin\\CategoryController:index' => '?',
            'App\\Controller\\admin\\CategoryController:new' => '?',
            'App\\Controller\\admin\\LoginAdminController:index' => '?',
            'App\\Controller\\admin\\ProductController:index' => '?',
            'App\\Controller\\admin\\ProductController:new' => '?',
            'App\\Controller\\user\\BuyController:index' => '?',
            'App\\Controller\\user\\BuyController:setNotificationUrl' => '?',
            'App\\Controller\\user\\BuyVacinController:index' => '?',
            'App\\Controller\\user\\CartController:add' => '?',
            'App\\Controller\\user\\CartController:remove' => '?',
            'App\\Controller\\user\\CartController:view' => '?',
            'App\\Controller\\user\\CategoryController:index' => '?',
            'App\\Controller\\user\\LoginController:index' => '?',
            'App\\Controller\\user\\PaymentController:reference' => '?',
            'App\\Controller\\user\\ProductsController:FindId' => '?',
            'App\\Controller\\user\\ProductsController:index' => '?',
            'App\\Controller\\user\\UserController:register' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
