<?php

namespace ContainerAPFWrOF;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_K1cqMOmService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.k1cqMOm' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.k1cqMOm'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'buyRepository' => ['services', 'App\\Repository\\BuyRepository', 'getBuyRepositoryService', true],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'logger' => ['privates', 'monolog.logger', 'getMonolog_LoggerService', false],
            'mercadoPagoService' => ['services', 'App\\Service\\MercadoPagoService', 'getMercadoPagoServiceService', true],
        ], [
            'buyRepository' => 'App\\Repository\\BuyRepository',
            'entityManager' => '?',
            'logger' => '?',
            'mercadoPagoService' => 'App\\Service\\MercadoPagoService',
        ]);
    }
}
