<?php

namespace ContainerAPFWrOF;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBuyService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Entity\Buy' shared autowired service.
     *
     * @return \App\Entity\Buy
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Entity/Buy.php';

        return $container->services['App\\Entity\\Buy'] = new \App\Entity\Buy();
    }
}
