<?php

namespace ContainerPKOiM7E;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_E0YnTc5Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.E0YnTc5' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.E0YnTc5'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'product' => ['services', 'App\\Repository\\ProductsRepository', 'getProductsRepositoryService', false],
        ], [
            'product' => 'App\\Repository\\ProductsRepository',
        ]);
    }
}
