<?php

namespace ContainerPKOiM7E;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_QcokgidService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.qcokgid' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.qcokgid'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'buyVacin' => ['services', 'App\\Repository\\BuyVacinRepository', 'getBuyVacinRepositoryService', true],
            'cart' => ['services', 'App\\Service\\CartService', 'getCartServiceService', false],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'mercadoPagoService' => ['services', 'App\\Service\\MercadoPagoService', 'getMercadoPagoServiceService', true],
            'productsRepository' => ['services', 'App\\Repository\\ProductsRepository', 'getProductsRepositoryService', false],
        ], [
            'buyVacin' => 'App\\Repository\\BuyVacinRepository',
            'cart' => 'App\\Service\\CartService',
            'entityManager' => '?',
            'mercadoPagoService' => 'App\\Service\\MercadoPagoService',
            'productsRepository' => 'App\\Repository\\ProductsRepository',
        ]);
    }
}
