<?php

namespace ContainerPKOiM7E;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Ol3XdKgService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.ol3XdKg' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.ol3XdKg'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'schoolVacinRepository' => ['services', 'App\\Repository\\SchoolVacinRepository', 'getSchoolVacinRepositoryService', true],
        ], [
            'entityManager' => '?',
            'schoolVacinRepository' => 'App\\Repository\\SchoolVacinRepository',
        ]);
    }
}
