<?php

namespace ContainerPKOiM7E;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getReturnMpRepositoryService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Repository\ReturnMpRepository' shared autowired service.
     *
     * @return \App\Repository\ReturnMpRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Repository/ReturnMpRepository.php';

        return $container->services['App\\Repository\\ReturnMpRepository'] = new \App\Repository\ReturnMpRepository(($container->services['doctrine'] ?? self::getDoctrineService($container)));
    }
}
