<?php

namespace ContainerPKOiM7E;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSchoolVacinRepositoryService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Repository\SchoolVacinRepository' shared autowired service.
     *
     * @return \App\Repository\SchoolVacinRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Repository/SchoolVacinRepository.php';

        return $container->services['App\\Repository\\SchoolVacinRepository'] = new \App\Repository\SchoolVacinRepository(($container->services['doctrine'] ?? self::getDoctrineService($container)));
    }
}
