<?php

namespace ContainerPKOiM7E;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSchoolVacinTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Form\SchoolVacinType' shared autowired service.
     *
     * @return \App\Form\SchoolVacinType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/SchoolVacinType.php';

        return $container->services['App\\Form\\SchoolVacinType'] = new \App\Form\SchoolVacinType();
    }
}
