<?php

namespace ContainerPKOiM7E;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSchoolVacinService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Entity\SchoolVacin' shared autowired service.
     *
     * @return \App\Entity\SchoolVacin
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Entity/SchoolVacin.php';

        return $container->services['App\\Entity\\SchoolVacin'] = new \App\Entity\SchoolVacin();
    }
}
