<?php

namespace Container3odRPi8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_U6HIRwVService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.u6HIRwV' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.u6HIRwV'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'productsRepository' => ['services', 'App\\Repository\\ProductsRepository', 'getProductsRepositoryService', false],
            'schoolVacinRepository' => ['services', 'App\\Repository\\SchoolVacinRepository', 'getSchoolVacinRepositoryService', true],
        ], [
            'productsRepository' => 'App\\Repository\\ProductsRepository',
            'schoolVacinRepository' => 'App\\Repository\\SchoolVacinRepository',
        ]);
    }
}
