<?php

namespace Container3odRPi8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_RcnNFGSService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.RcnNFGS' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.RcnNFGS'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'banners' => ['services', 'App\\Repository\\BannerRepository', 'getBannerRepositoryService', true],
        ], [
            'banners' => 'App\\Repository\\BannerRepository',
        ]);
    }
}
