<?php

namespace Container3odRPi8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBannerRepositoryService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Repository\BannerRepository' shared autowired service.
     *
     * @return \App\Repository\BannerRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Repository/BannerRepository.php';

        return $container->services['App\\Repository\\BannerRepository'] = new \App\Repository\BannerRepository(($container->services['doctrine'] ?? self::getDoctrineService($container)));
    }
}
