<?php

namespace Container3odRPi8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBannerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Entity\Banner' shared autowired service.
     *
     * @return \App\Entity\Banner
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Entity/Banner.php';

        return $container->services['App\\Entity\\Banner'] = new \App\Entity\Banner();
    }
}
