<?php

namespace Container3odRPi8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getStatusControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\user\StatusController' shared autowired service.
     *
     * @return \App\Controller\user\StatusController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/user/StatusController.php';

        $container->services['App\\Controller\\user\\StatusController'] = $instance = new \App\Controller\user\StatusController(($container->services['App\\Repository\\BuyRepository'] ?? $container->load('getBuyRepositoryService')));

        $instance->setContainer(($container->privates['.service_locator.O2p6Lk7'] ?? $container->load('get_ServiceLocator_O2p6Lk7Service'))->withContext('App\\Controller\\user\\StatusController', $container));

        return $instance;
    }
}
