<?php

namespace Container3odRPi8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUserCheckerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Security\Checkers\UserChecker' shared autowired service.
     *
     * @return \App\Security\Checkers\UserChecker
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/security-core/User/UserCheckerInterface.php';
        include_once \dirname(__DIR__, 4).'/src/Security/Checkers/UserChecker.php';

        return $container->services['App\\Security\\Checkers\\UserChecker'] = new \App\Security\Checkers\UserChecker();
    }
}
