# config/routes.yaml
controllers:
  resource:
    path: ../src/Controller/
    namespace: App\Controller
  type: annotation

app_logout:
  path: /logout

admin_logout:
  path: /admin/logout

app_product_new:
  path: /admin/product/new
  controller: App\Controller\admin\ProductController::new

app_product_id:
  path: /product/{id}
  controller: App\Controller\user\ProductsController::FindId

cart_add:
  path: /cart/add/{productId}/{quantity}/{BuyId}
  controller: App\Controller\user\CartController::add

cart_view:
  path: /cart/view
  controller: App\Controller\user\CartController::view

cart_remove:
  path: /cart/remove/{productId}
  controller: App\Controller\user\CartController::remove

payment_update_reference:
  path: /update/reference/{reference}
  controller: App\Controller\user\PaymentController::reference