<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerDzARamB\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerDzARamB/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerDzARamB.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerDzARamB\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerDzARamB\App_KernelDevDebugContainer([
    'container.build_hash' => 'DzARamB',
    'container.build_id' => '9eda9ad4',
    'container.build_time' => 1679974499,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerDzARamB');
