<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerYwy0oLR\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerYwy0oLR/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerYwy0oLR.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerYwy0oLR\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerYwy0oLR\App_KernelDevDebugContainer([
    'container.build_hash' => 'Ywy0oLR',
    'container.build_id' => '0348bcdb',
    'container.build_time' => 1680035703,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerYwy0oLR');
