<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPKOiM7E\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPKOiM7E/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerPKOiM7E.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerPKOiM7E\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerPKOiM7E\App_KernelDevDebugContainer([
    'container.build_hash' => 'PKOiM7E',
    'container.build_id' => '1bbf1c65',
    'container.build_time' => 1680113699,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPKOiM7E');
