<?php

namespace ContainerYwy0oLR;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_CEbZNOService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.CEbZ_nO' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.CEbZ_nO'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'cart' => ['services', 'App\\Service\\CartService', 'getCartServiceService', false],
            'productRepository' => ['services', 'App\\Repository\\ProductsRepository', 'getProductsRepositoryService', false],
        ], [
            'cart' => 'App\\Service\\CartService',
            'productRepository' => 'App\\Repository\\ProductsRepository',
        ]);
    }
}
