<?php

namespace ContainerYwy0oLR;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_6awHTOwService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.6awHTOw' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.6awHTOw'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'preference' => ['privates', '.errored..service_locator.6awHTOw.MercadoPago\\Preference', NULL, 'Cannot autowire service ".service_locator.6awHTOw": it references class "MercadoPago\\Preference" but no such service exists.'],
        ], [
            'preference' => 'MercadoPago\\Preference',
        ]);
    }
}
