<?php

namespace ContainerYwy0oLR;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBuyVacinService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Entity\BuyVacin' shared autowired service.
     *
     * @return \App\Entity\BuyVacin
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Entity/BuyVacin.php';

        return $container->services['App\\Entity\\BuyVacin'] = new \App\Entity\BuyVacin();
    }
}
