<?php

namespace ContainerYwy0oLR;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPreferenceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.6awHTOw.MercadoPago\Preference' shared service.
     *
     * @return \MercadoPago\Preference
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.6awHTOw": it references class "MercadoPago\\Preference" but no such service exists.');
    }
}
